- ctx.go
- libs/validator/check.go
- libs/validator/validator.go
> support custom validate

- app.go
add judge if gin use middleware cors
> [fix] add judge if gin use middleware cors

- .github/CODEOWNERS
- app.go
- base/basethird/http.go
- ctx.go
- yago/version.go
1. add return error for ctx request method
2. add http client options
> moded: http client

- base/basethird/http.go
- base/basethird/rpc.go
- example/app/modules/home/homecmd/home.go
- example/app/third/homeapi/home.go
- example/app/third/homeapi/home_rpc.go
- example/conf/app.toml
- go.mod
> feat:  add InitConfig method in httpthird and rpcthird

- example/app/modules/home/homedao/home.go
- example/app/modules/home/homehttp/home.go
> feat: change example homehttp example validator

- base/basethird/rpc.go
- example/app/modules/home/homecmd/home.go
- example/app/third/homeapi/home_rpc.go
- go.mod
> feat: change base rpc third client interceptor

- coms/etcd/etcd.go
- coms/etcd/etcd_test.go
- example/conf/app.toml
- go.mod
Signed-off-by: lidequan <lidequan@360.cn>
> feat: add etcd component

- yago/main.go
- yago/template.go
> feat: add gen cmd for yago, autogen http, rpc, cmd, task, model file

- app.go
> feat: recover panic when debug mode is false

- base/basethird/http.go
> fix: add Files in request option

- example/app/modules/home/homehttp/home.go
- router.go
- yago/main.go
- yago/template.go
- yago/version.go
> feat: add metadata for http router

- com.go
- coms/rds/redis.go
- coms/rds/redis_cmd.go
- coms/rds/redis_test.go
- conf.go
- go.mod
- sig.go
> feat: kill -USR2 pid  -> reload config in runtime

- base/basethird/http.go
- example/app/third/homeapi/home.go
> feat: add http third middleware interceptor

- base/basehttp/default_validator.go
- base/basethird/http.go
- conf.go
- libs/validatelib/validator.go
Signed-off-by: zhangjiulong <l-zhangxiaobao@qianxin.com>
> bug: change validatelib.New() to Ins() for return a sigleton

- base/basethird/http.go
Signed-off-by: zhangjiulong <l-zhangxiaobao@qianxin.com>
> feat: add requestbody in http

- conf.go
同时支持
go test 
go test -v
go test -args="-c=/path/app.toml"
> feat: 解决 go test 不需要使用配置文件时的报错问题

- base/basetask/task.go
锁如果报错，则会重新获取锁，重新执行handlerFunc()
如果，上次的handlerFunc()还在执行中，
这样就会导致多个handlerFunc()并行执行。
> fix:修复redis失败导致多个handlerFunc同时运行的bug

- libs/treelib/tree.go
- libs/treelib/tree_test.go
> feat: add tree lib

- libs/promiselib/promise.go
- libs/promiselib/promise_test.go
don't wait for all goruntine to finish when error
we should return immediately
> feat:trigger error returns early for concurrency

- go.mod
- libs/excellib/excel.go
- libs/excellib/excel_test.go
* 新增 excellib 库，支持导入文件，导入流，导出，导出并自动调整宽度等
> feat: add excellib

- coms/locker/redis/redis.go
> feat: close connect after unlock

- ctx.go
> feat: 错误时不返回 data 信息

- app.go
- example/app/modules/home/homehttp/homemiddleware/user.go
- example/app/modules/home/homehttp/user.go
- router.go
- yago/main.go
- yago/version.go
* 废弃 http AddHttpRouter
* 新增单个 http router 上使用多个 middleware
* 优化 http router metadata 的使用方式
> fix: 增加单个的路由中间件的使用，优化 metadata 的使用方式

- example/app/g/middleware/bizlog.go
> feat: refine bizlog

- base/basehttp/default_validator.go
> fix: support slice params

- coms/orm/orm.go
##BUGFIX
* 当创建 Orm 实例失败时打印错误信息
> feat: 当 orm 创建引擎错误时终止进程

- base/basethird/http.go
- coms/locker/redis/redis.go
- error.go
* 增加 HTTPCodeError，用于根据 third 返回的 http 错误码做不同处理
* 增强 redis 锁，解决 goroutine 泄露
> F third code err

- libs/str/str.go
- libs/str/str_test.go
> feat: add substr method in str lib

- README.md
> feat: add special thanks to idea

- base/basethird/http.go
- libs/mathlib/math.go
- libs/mathlib/math_test.go
> B third log size

- app.go
- conf.go
- ctx.go
- example/conf/app.toml
* 增加 https_addr 参数，支持 http 与 https 同时提供服务 
* 支持使用环境变量 YAGO_CONF 设置默认配置文件，解决 go test 配置文件的问题
* 将 json marshal 错误码设置为2
> F default conf

- app.go
- coms/etcd/etcd.go
- coms/etcd/etcd_test.go
- coms/locker/etcd/etcd.go
- go.mod
* 升级etcd版本到v3.5.3解决[DNS Rebinding in etcd]漏洞
> feat: 升级 etcd 到 v3.5.4
